#!/bin/bash

# Create a new librenms user and remap it to the given UID
if [ ! -z "$PUID" ]; then
  if [ -z "$PGID" ]; then
    PGID=${PUID}
  fi
  groupmod --gid ${PGID} librenms
  usermod -u ${PUID} librenms
fi

# Don't `chown` if SKIP_CHOWN is set (Useful for NFS mounted shares) 
if [ -z "$SKIP_CHOWN" ]; then
  
  if [ -f /opt/librenms/config.custom.php ]; then
  	chown librenms:librenms /opt/librenms/config.custom.php || true
  fi

  chown -R librenms:librenms /opt/librenms/conf.d /opt/librenms/logs /opt/librenms/rrd || true
  chmod -R u=rwX,g=rwX,o=rX /opt/librenms/conf.d /opt/librenms/logs /opt/librenms/rrd || true
  # Note || true after the chown avoids potential problems 
  # when mounting volumes via NFS
fi

exit 0
